### PR TITLE
Add missing devDependency to package.json

### PR DESCRIPTION
**Pull request by iMoses-Apiiro**
without `@emotion/react` tests will not run

### CODE REVIEW

**Comment by tmcneal** [comment]
Hi @iMoses-Apiiro, thank you for the PR. I've just tried replicating this issue by deleting the node_modules directory and running `npm install && npm run test` and the tests are working for me. Could you try that and see if the tests now pass? If not can you paste the console output when you attempt to run the tests?

**Comment by iMoses-Apiiro** [comment]
@tmcneal same for me, the tests are running but all failing because of the missing package.
can you make sure that the library isn't installed on a higher level on your machine, maybe globally?

**Comment by tmcneal** [comment]
This is very odd. Someone on our team who has never built this plugin before was able to build and run the tests without issue, and we confirmed that they don't have any packages installed globally except for npm itself. I'm honestly not sure why you're hitting this...

**Comment by iMoses-Apiiro** [comment]
That is weird... I can try cloning the repo into a docker container and see if it reproduces on a clean environment. Guess that'll give us a better understanding.

BTW, which version of NPM are you using? It could be related.

**Comment by tmcneal** [comment]
OK thanks - if it still occurs I'm fine to merge this since it's just a dev dependency anyway - I was just trying to avoid it if I could.

I'm on version `v17.2.0` of node and version `8.1.4` of npm

**Comment by tmcneal** [comment]
@iMoses-Apiiro I'm going to close this PR since I had multiple folks validate that they didn't hit this issue on their local environments - hopefully upgrading npm and node fixes it for you.

**Pull request closed without merging**
